
publish:
  docker:
    file: 2.0/Dockerfile
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/elasticsearch
    tag: latest
    force_tag: true
    storage_driver: overlay
